apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: react2shell-poc-cluster
  region: us-east-1

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true # public key must be present in ~/.ssh/id_rsa.pub or similar
    # Using a standard AL2 image
